{{ if .Values.additionalStorage.useHostDir }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.additionalStorage.name | default "geodata"}}
spec:
  {{- with .Values.additionalStorage }}
  capacity:
    storage: {{ .fmeserver.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy }}
  hostPath:
    path: {{ .fmeserver.path | default "/tmp/k8s/geodata" }}
    type: DirectoryOrCreate
  {{- end }}
{{- end}}