{{- if .Values.deployment.ingress.enabled }}
apiVersion: {{ include "fmeflow.ingress.apiversion" . }}
kind: Ingress
metadata:
  name: fmeflow-remoteengine-web-ingress
  annotations:
    {{- if and .Values.deployment.useHostnameIngress .Values.deployment.ingress.useNginxMergeable }}
    nginx.org/mergeable-ingress-type: "minion"
    {{- end }}
{{- if .Values.deployment.ingress.annotations }}
{{ toYaml .Values.deployment.ingress.annotations | indent 4 }}
{{ end }}
{{- include "fmeflow.ingress.annotations" . | indent 4 }}
spec:
  ingressClassName: {{ .Values.deployment.ingress.ingressClassName }}
  {{- if not (and .Values.deployment.useHostnameIngress .Values.deployment.ingress.useNginxMergeable) }}
  {{- include "fmeflow.ingress.tls" . }}
  {{- end }}
  rules:
    - http:
        paths:
          - backend:
{{ include "fmeflow.ingress.web.service" . | indent 14 }}
            path: /
            {{ include "fmeflow.ingress.pathType" . }}
      {{- if .Values.deployment.useHostnameIngress }}
      host: {{ .Values.deployment.hostname }}
      {{ end }}
{{- end }}
