apiVersion: v1
kind: Service
metadata:
  labels:
    safe.k8s.fmeflow.component: web
    {{- include "fmeflow.common.labels" . | indent 4 }}
  {{- with .Values.annotations.core.service }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: fmeflowweb
spec:
  ports:
  - port: 8080
  selector:
    safe.k8s.fmeflow.component: core