apiVersion: v1
kind: Service
metadata:
  labels:
    safe.k8s.fmeflow.component: core
    {{- include "fmeflow.common.labels" . | indent 4 }}
  {{- with .Values.annotations.core.service }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: fmeflow
spec:
  clusterIP: None
  ports:
    - name: engineregistration
      port: 7070
  selector:
    safe.k8s.fmeflow.component: core
