{{- if and (not .Values.deployment.disableTLS) (empty .Values.deployment.tlsSecretName) }}
{{- $secretName := include "fmeflow.ingress.tlsSecretName" . }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: kubernetes.io/tls
data:
{{- if and $existing (index $existing.data "tls.crt") (index $existing.data "tls.key") }}
  tls.crt: {{ index $existing.data "tls.crt" }}
  tls.key: {{ index $existing.data "tls.key" }}
{{- else }}
  {{- $ca := genCA (printf "%s-ca" (include "fmeflow.fullname" .)) 3650 }}
  {{- $cert := genSignedCert .Values.deployment.hostname nil (list .Values.deployment.hostname) 3650 $ca }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end }}
