apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    safe.k8s.fmeflow.component: websocket
    {{- include "fmeflow.common.labels" . | indent 4 }}
  name: websocket
  {{- with .Values.annotations.websocket.statefulset }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      safe.k8s.fmeflow.component: websocket
  serviceName: fmeflowwebsocket
  template:
    metadata:
      labels:
        safe.k8s.fmeflow.component: websocket
        {{- include "fmeflow.common.labels" . | indent 8 }}
        {{- with .Values.labels.websocket }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- with .Values.annotations.websocket.template }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - image: {{ template "fmeflow.image.registry" . }}/{{ template "fmeflow.image.namespace" . }}/fmeflow-core:{{ template "fmeflow.image.tag" . }}
          name: websocket
          imagePullPolicy: {{ template "fmeflow.image.pullPolicy" . }}
          env:
            - name: PRIMARY_PROCESS
              value: websocket
          ports:
            - containerPort: 7078
          volumeMounts:
            - mountPath: /data/fmeflowdata
              name: fmeflowdata
              {{- if .Values.storage.fmeflow.volumePath }}
              subPath: {{ .Values.storage.fmeflow.volumePath }}
              {{- end }}
          resources:
{{ toYaml .Values.resources.websocket | indent 12 }}
          livenessProbe:
            tcpSocket:
              port: 7078
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 7078
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
      restartPolicy: Always
      volumes:
        - name: fmeflowdata
          persistentVolumeClaim:
            claimName: {{ template "fmeflow.storage.data.claimName" . }}
      affinity:
        {{- include "fmeflow.deployment.dataVolumeAffinity" . | indent 8 }}
      {{- if .Values.scheduling.websocket.affinity }}
{{ toYaml .Values.scheduling.websocket.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.scheduling.websocket.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.scheduling.websocket.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.scheduling.websocket.tolerations }}
      tolerations:
{{ toYaml .Values.scheduling.websocket.tolerations | indent 8 }}
      {{- end }}
